export const FETCH_ITEMS = 'ITEMS::FETCH';
export const FETCH_ITEMS_COMPLETED = 'ITEMS::FETCH_COMPLETED';
export const FETCH_ITEMS_FAILED = 'ITEMS::FETCH_FAILED';

export const UPLOAD_ITEM = 'ITEM_UPLOAD';

export const REMOVE_ITEM = 'ITEMS::REMOVE';
export const UPDATE_ITEM = 'ITEMS::UPDATE';

export const ADD_FILES_TO_ITEM = 'ITEMS::ADD_FILES_TO_ITEM';

export const FETCH_LINK_IMPORTS = 'ITEMS::FETCH_LINK_IMPORTS';
export const FETCH_LINK_IMPORT_FAILED = 'ITEMS::FETCH_LINK_IMPORT_FAILED';

export const SAVE_SELECTED_MED = 'ITEMS::SAVE_SELECTED_MED';
export const SAVE_SELECTED_MED_COMPLETED = 'ITEMS::SAVE_SELECTED_MED_COMPLETED';
export const SAVE_SELECTED_MED_FAILED = 'ITEMS::SAVE_SELECTED_MED_FAILED';

export const SET_ITEM_THUMBNAIL_URL = 'ITEMS::SET_THUMBNAIL_URL';
