export const SUBMIT_TICKET = 'HELP_DESK::SUBMIT_TICKET';
export const SUBMIT_TICKET_SUCCESS = 'HELP_DESK::SUBMIT_TICKET_SUCCESS';
export const SUBMIT_TICKET_FAILED = 'HELP_DESK::SUBMIT_TICKET_FAILED';
