export const ERROR = 'MIXPANEL::ERROR';
export const TRACK = 'MIXPANEL::TRACK';
export const SET_GROUP = 'MIXPANEL::SET_GROUP';
export const SET_SCREEN_NAME = 'MIXPANEL::SET_SCREEN_NAME';
export const SET_USER_PROPERTY = 'MIXPANEL::SET_USER_PROPERTY';
export const CREATE_ALIAS = 'MIXPANEL::CREATE_ALIAS';
export const IDENTIFY = 'MIXPANEL::IDENTIFY';
