export const CHANGE_FLOW = 'ONBOARDING::CHANGE_FLOW';
export const ADD_FORM_DATA = 'ONBOARDING::ADD_FORM_DATA';
export const SET_PIN_CODE = 'ONBOARDING::SET_PIN_CODE';
export const CLEAR_FORM_DATA = 'ONBOARDING::CLEAR_FORM_DATA';

export const REGISTER = 'ONBOARDING::REGISTER';
export const REGISTER_FAILED = 'ONBOARDING::REGISTER_FAILED';

export const LOGIN = 'ONBOARDING::LOGIN';
export const LOGIN_FAILED = 'ONBOARDING::LOGIN_FAILED';

export const REGISTER_PROFILE = 'ONBOARDING::REGISTER_PROFILE';
export const REGISTER_PROFILE_FAILED = 'ONBOARDING::REGISTER_PROFILE_FAILED';

export const LOOKUP_RESULTS = 'ONBOARDING::LOOKUP_RESULTS';
export const LOOKUP_NOOP = 'ONBOARDING::LOOKUP_NOOP';
export const SET_REGISTERING_AS_CAREGIVER = 'ONBOARDING::SET_REGISTER_AS_CAREGIVER';

export const ONBOARDING_DISMISSED = 'ONBOARDING::DISMISSED';
