export const UPLOAD_STARTED = 'UPLOADS::UPLOAD_STARTED';
export const FILE_UPLOAD_COMPLETE = 'UPLOADS::FILE_UPLOAD_COMPLETE';
export const FILE_UPLOAD_FAILED = 'UPLOADS::FILE_UPLOAD_FAILED';
export const TRY_AGAIN = 'UPLOADS::TRY_AGAIN';
