export const DISABLE_SHARED_LINKS = 'SHARE::DISABLE_SHARED_LINKS';
export const LOAD_SHARED_ITEM_SUCCESS = 'SHARE::LOAD_SHARED_ITEM_SUCCESS';
export const LOAD_SHARED_ITEM_FAILED = 'SHARE::LOAD_SHARED_ITEM_FAILED';
export const SELECT_ITEM = 'SHARE::SELECT_ITEM';
export const UPDATE_SHARED_LINK = 'SHARE::UPDATE_SHARED_LINK';
