export const ENABLE_BIOMETRIC_AUTH = 'BIOMETRIC_AUTH_SETTINGS::ENABLE_AUTH';
export const ENABLE_BIOMETRIC_AUTH_SUCCESS = 'BIOMETRIC_AUTH_SETTINGS::ENABLE_SUCCESS';
export const DISABLE_BIOMETRIC_AUTH = 'BIOMETRIC_AUTH_SETTINGS::DISABLE';
export const DISABLE_BIOMETRIC_AUTH_SUCCESS = 'BIOMETRIC_AUTH_SETTINGS::DISABLE_SUCCESS';
export const CHECK_BIOMETRIC_SUPPORT = 'BIOMETRIC_AUTH_SETTINGS::CHECK_BIOMETRIC_SUPPORT';
export const CHECK_BIOMETRIC_SUPPORT_SUCCESS = 'BIOMETRIC_AUTH_SETTINGS::CHECK_BIOMETRIC_SUPPORT_SUCCESS';
export const CHECK_BIOMETRIC_SUPPORT_REJECTED = 'BIOMETRIC_AUTH_SETTINGS::CHECK_BIOMETRIC_SUPPORT_REJECTED';
